# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'sequence':-100,
    'category': 'Hospital',
    'summary': 'Hospital management system',
    'description':"""""",
    'depends': ['mail','product','xlsx_reporting','om_odoo_inheritance','base', 'crm','sale','website','web','om_account_accountant',
                'om_account_budget','om_account_daily_reports','accounting_pdf_reports','om_account_asset','om_account_followup','om_fiscal_year','sale_service','stock','point_of_sale'],
    'data': [
        'security/hospital_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/patient_tag.xml',
        'data/cron_data.xml',
        #'data/custom_delivery_order_data.xml',
        'data/patient.tag.csv',
        'data/sequence_data.xml',
        'data/mail_template.xml',
        'wizard/create_appointment.xml',
        'wizard/sale_order_wizard.xml',
        'views/res_config_setting.xml',
        #'views/website_form.xml',
        'views/appointment_website_form.xml',
        'views/menuitem.xml',
        'views/female_patient.xml',
        'views/appointment.xml',
        'views/patient_tag.xml',
        'views/template.xml',
        'views/sale_order_data_inherit.xml',
        'views/doctor.xml',
        'views/pharmacy_data.xml',
        'views/create_patient_js.xml',
        'views/dashboard.xml',
        'views/create_patient_website.xml',
        'views/ajax_controller_button.xml',
        'views/pos_custom_template.xml',
        #'views/favourite_patient.xml',
        #'views/asset.xml',
        'reports/report.xml',
        'reports/inherit_report.xml',
        'reports/sale_order_data.xml',
    ],
    'assets': {
        # 'point_of_sale._assets_pos':[
        #     '/om_hospital/static/src/xml/pos_variant_pop.xml',
        #     '/om_hospital/static/src/js/pos_custom.js',
        #     '/om_hospital/static/src/js/print.js',
        #     '/om_hospital/static/src/js/pos_variant_pop.js',
        # ],
        'web.assets_frontend':[
            '/om_hospital/static/src/xml/create_patient_js.xml',
            '/om_hospital/static/src/js/ajax_controller.js',
            '/om_hospital/static/src/xml/ajax_controller.xml',
        ],
        'web.assets_backend': [
            '/om_hospital/static/src/js/create_patient_dialog.js',
            '/om_hospital/static/src/css/create_patient.css',
            '/om_hospital/static/src/js/chart.js',
            '/om_hospital/static/src/js/create_dashboard.js',
            '/om_hospital/static/src/xml/create_dashboard.xml',
            # '/om_hospital/static/src/js/patient_kanban.js',
            # '/om_hospital/static/src/xml/patient_kanban.xml',
            #'/om_hospital/static/src/js/pos_custom.js',

        ],
    },
    'demo': [],
    'installation': True,
    'auto_install': False,
    'licence': 'LGPL-3',
    'application': True,

}
